### PR TITLE
#11 Update Author Info

### LINKED ISSUE #11: Plugin Author/link incorrect
## Bug Report

When viewing the main Plugins page, the author and link are incorrect.

Current author: John Parris
Current link: http://www.johnparris.com/wordpress-plugins/edd-recently-viewed-items

Screenshot_2021-01-27 Plugins ‹ EDD Doc Test — WordPress

### PR DESCRIPTION
**Pull request by LisaCee**
Fixes #11

Proposed Changes:

1. Update author from John Parris to Sandhills
2. Add item id to license
3. Update URLs for plugin and author

### CODE REVIEW

**Comment by shaynesanderson** [comment]
@LisaCee Looks great!

**Review by ashleyfae — APPROVED** [review]

File: edd-recently-viewed-items.php [hunk 1]
```diff
@@ -1,11 +1,11 @@
...
 /**
  * Plugin Name: Easy Digital Downloads - Recently Viewed Items
- * Plugin URI: http://www.johnparris.com/wordpress-plugins/edd-recently-viewed-items
+ * Plugin URI: https://easydigitaldownloads.com/downloads/recently-viewed-items/
  * Description: Show your visitors the items they've recently viewed with this extension for Easy Digital Downloads.
  * Version: 1.0.2
- * Author: John Parris
- * Author URI: http://www.johnparris.com
+ * Author: Sandhills Development, LLC
+ * Author URI: http://www.sandhillsdev.com
```
Comment (robincornett) [inline edd-recently-viewed-items.php:8]: Sorry, can this be `https` instead? Finicky, I know. Everything else looks great!

**Review by robincornett — APPROVED** [review]
